version: "3.3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./asset:/app/asset
      - ./src:/app/src
      - ./config:/app/config
      - ./utils:/app/utils
    links:
      - mongo
    environment:
      NODE_ENV: dev
  mongo:
    ports:
      - "27017:27017"
    image: mongo
    volumes:
      - db_data:/data/db
volumes:
  db_data:
